{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
  name: {{ template "metallb.fullname" . }}
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - {{ .Values.config.addresses }}
{{- end }}