apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
  name: {{ template "metallb.fullname" . }}-config-watcher
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch