apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: metallb
  name: {{ template "metallb.fullname" . }}:speaker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "metallb.fullname" . }}:speaker
subjects:
- kind: ServiceAccount
  name: {{ template "metallb.fullname" . }}-speaker
  namespace: {{ .Release.Namespace }}